# Generated by Django 4.0.2 on 2022-02-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('cpf', models.CharField(max_length=25, unique=True)),
                ('tipo', models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'publicador'), (3, 'comun')])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
