# Generated by Django 4.0.2 on 2022-02-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'publicador'), (3, 'comun')], null=True),
        ),
    ]
