# Generated by Django 4.0.2 on 2022-02-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0002_alter_user_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
